syntax = "proto3";

package jobposting;

service JobPostingService {
  rpc GetJob (GetJobRequest) returns (Job);
  rpc ListJobs (ListJobsRequest) returns (ListJobsResponse);
}

message GetJobRequest {
  string job_id = 1;
}

message ListJobsRequest {
  string query = 1;
  repeated string skills = 2;
}

message Job {
  string job_id = 1;
  string title = 2;
  string description = 3;
  repeated string required_skills = 4;
  repeated string requirements = 5;
}

message ListJobsResponse {
  repeated Job jobs = 1;
}
